/**
 * osiTcpipVisualizer.js — Encapsulation & Decapsulation Simulator
 * Premium visual overhaul: nested packet diagram, animated data flow,
 * glassmorphism layer cards, glowing active states, and rich step info.
 */

import { stateManager } from '../js/stateManager.js';
import { OsiQuizMode } from './osiQuizMode.js';

/* ── Layer Definitions ── */
const OSI_LAYERS = [
  { num: 7, name: 'Application', color: '#EF5350', pdu: 'Data', header: 'HTTP/DNS/FTP', icon: '📡', detail: 'User data is generated by the application.', headerSize: 0 },
  { num: 4, name: 'Transport', color: '#5C6BC0', pdu: 'Segment', header: 'TCP / UDP', icon: '🔀', detail: 'Source & destination ports added. Segmentation & flow control.', headerSize: 20 },
  { num: 3, name: 'Network', color: '#26A69A', pdu: 'Packet', header: 'IPv4 / IPv6', icon: '🌐', detail: 'Source & destination IP addresses added. Routing decisions.', headerSize: 20 },
  { num: 2, name: 'Data Link', color: '#EC407A', pdu: 'Frame', header: 'Ethernet', icon: '🔗', detail: 'Source & destination MAC addresses + FCS trailer added.', headerSize: 14 },
  { num: 1, name: 'Physical', color: '#AB47BC', pdu: 'Bits', header: 'Electrical/Optical', icon: '⚡', detail: 'Frame converted to raw bits for transmission on the wire.', headerSize: 0 },
];

/* ── Encapsulation step descriptions ── */
const ENCAP_STEPS = [
  { title: 'Ready', desc: 'Press Play or Step to begin the encapsulation process.', activeLayer: -1 },
  {
    title: 'Data Created', desc: 'The Application layer generates the payload — e.g. an HTTP GET request.', activeLayer: 7,
    packetLabel: 'DATA', fields: '"Hello World!"'
  },
  {
    title: 'TCP Header Added', desc: 'Transport wraps the data in a TCP segment with port numbers (443 → 54321) and sequence info.', activeLayer: 4,
    packetLabel: 'TCP HDR', fields: 'Src Port: 443 → Dst Port: 54321'
  },
  {
    title: 'IP Header Added', desc: 'Network layer adds logical addressing — source and destination IP addresses.', activeLayer: 3,
    packetLabel: 'IP HDR', fields: 'Src: 192.168.1.10 → Dst: 8.8.8.8'
  },
  {
    title: 'Ethernet Frame', desc: 'Data Link adds a MAC header & FCS trailer for local delivery on the LAN.', activeLayer: 2,
    packetLabel: 'ETH HDR', fields: 'Src MAC: AA:BB:CC → Dst MAC: FF:FF:FF'
  },
  {
    title: 'Bit Transmission', desc: 'The Physical layer converts the entire frame into electrical signals or light pulses.', activeLayer: 1,
    packetLabel: 'BITS', fields: '01101000 01100101 01101100 01101100 01101111...'
  },
];

const DEENCAP_STEPS = [
  { title: 'Ready', desc: 'Press Play or Step to begin the de-encapsulation process.', activeLayer: -1 },
  {
    title: 'Bits Received', desc: 'Physical layer receives raw electrical signals and reconstructs the frame.', activeLayer: 1,
    removedLabel: 'BITS → FRAME'
  },
  {
    title: 'Ethernet Stripped', desc: 'Data Link examines MAC addresses & FCS, then strips the Ethernet header.', activeLayer: 2,
    removedLabel: 'ETH HDR ✓'
  },
  {
    title: 'IP Header Removed', desc: 'Network layer reads the destination IP, confirms it matches, and removes the IP header.', activeLayer: 3,
    removedLabel: 'IP HDR ✓'
  },
  {
    title: 'TCP Header Removed', desc: 'Transport reassembles segments, checks sequence numbers, and strips the TCP header.', activeLayer: 4,
    removedLabel: 'TCP HDR ✓'
  },
  {
    title: 'Data Delivered', desc: 'Clean application data is delivered to the receiving application — message received!', activeLayer: 7,
    removedLabel: 'DATA ✓'
  },
];

class OsiTcpipVisualizer {
  constructor() {
    this.container = null;
    this._phase = 'ENCAPSULATION';
    this._isPlaying = false;
    this._currentStep = 0;
    this._playSpeed = 1;
    this._data = 'Hello World!';
    this._quizInstance = null;
    this._autoTimer = null;
  }

  init(containerEl) {
    this.container = containerEl;
    this._render();
  }

  /* ══════════════════════════════════════════
     MAIN RENDER
     ══════════════════════════════════════════ */
  _render() {
    const steps = this._phase === 'ENCAPSULATION' ? ENCAP_STEPS : DEENCAP_STEPS;

    this.container.innerHTML = `
      <style>
        .osi-viz { --glow-cyan: rgba(0,206,209,0.35); }

        /* ── Mode Toggle ── */
        .osi-mode-toggle {
          display:flex; background:rgba(0,0,0,0.3); border-radius:12px; padding:4px; gap:4px; margin-bottom:1.5rem;
        }
        .osi-mode-btn {
          flex:1; padding:0.65rem 1rem; border:none; border-radius:9px; font-weight:700; font-size:0.85rem;
          cursor:pointer; transition:all 0.3s ease; font-family:inherit; text-transform:uppercase; letter-spacing:0.08em;
        }
        .osi-mode-btn.active {
          background:linear-gradient(135deg, #00CED1, #0099aa); color:#000; box-shadow:0 2px 16px rgba(0,206,209,0.35);
        }
        .osi-mode-btn:not(.active) {
          background:transparent; color:var(--color-text-muted); border:none;
        }
        .osi-mode-btn:not(.active):hover { color:var(--color-text-primary); background:rgba(255,255,255,0.04); }

        /* ── Transport Controls ── */
        .osi-controls {
          display:flex; align-items:center; gap:0.6rem; padding:0.8rem 1rem;
          background:rgba(0,0,0,0.25); border:1px solid rgba(255,255,255,0.06);
          border-radius:14px; margin-bottom:1.5rem; flex-wrap:wrap;
        }
        .osi-ctrl-btn {
          display:inline-flex; align-items:center; gap:6px;
          padding:0.45rem 0.9rem; border-radius:8px; font-weight:600; font-size:0.82rem;
          cursor:pointer; transition:all 0.2s; font-family:inherit; border:1px solid rgba(255,255,255,0.1);
          background:rgba(255,255,255,0.04); color:var(--color-text-secondary);
        }
        .osi-ctrl-btn:hover { background:rgba(255,255,255,0.1); border-color:rgba(255,255,255,0.2); }
        .osi-ctrl-btn.primary { background:linear-gradient(135deg,#00CED1,#0099aa); color:#000; border:none; font-weight:700; }
        .osi-ctrl-btn.primary:hover { box-shadow:0 2px 16px rgba(0,206,209,0.4); transform:translateY(-1px); }
        .osi-speed-chip {
          padding:0.3rem 0.55rem; border-radius:6px; font-size:0.75rem; font-weight:600;
          cursor:pointer; transition:all 0.2s; font-family:var(--font-mono);
          background:rgba(255,255,255,0.05); border:1px solid rgba(255,255,255,0.08); color:var(--color-text-muted);
        }
        .osi-speed-chip.active { background:#00CED1; color:#000; border-color:#00CED1; font-weight:700; }
        .osi-speed-chip:hover:not(.active) { background:rgba(255,255,255,0.1); }

        /* ── Layer Cards ── */
        .osi-layer-card {
          position:relative; display:flex; align-items:stretch; gap:0;
          border-radius:12px; overflow:hidden; transition:all 0.4s cubic-bezier(0.4,0,0.2,1);
          border:1px solid rgba(255,255,255,0.06); background:rgba(0,0,0,0.2);
        }
        .osi-layer-card .lc-accent {
          width:5px; flex-shrink:0; transition:all 0.4s ease;
        }
        .osi-layer-card .lc-body {
          flex:1; padding:0.9rem 1rem; display:flex; align-items:center; gap:0.85rem; position:relative;
        }
        .osi-layer-card .lc-badge {
          width:42px; height:42px; border-radius:10px; display:flex; align-items:center; justify-content:center;
          font-weight:800; font-size:0.95rem; color:white; flex-shrink:0; transition:all 0.4s ease;
          position:relative;
        }
        .osi-layer-card .lc-info { flex:1; min-width:0; }
        .osi-layer-card .lc-name { font-weight:700; font-size:0.95rem; color:var(--color-text-primary); }
        .osi-layer-card .lc-sub { font-size:0.75rem; color:var(--color-text-muted); font-family:var(--font-mono); margin-top:2px; }
        .osi-layer-card .lc-pdu {
          padding:0.2rem 0.5rem; border-radius:6px; font-size:0.7rem; font-weight:700;
          text-transform:uppercase; letter-spacing:0.08em; white-space:nowrap;
          transition:all 0.4s ease;
        }
        .osi-layer-card .lc-status {
          font-size:0.8rem; font-family:var(--font-mono); color:var(--color-text-muted);
          padding:0.35rem 0.65rem; border-radius:6px; background:rgba(0,0,0,0.2);
          transition:all 0.4s ease; white-space:nowrap;
        }

        /* Active layer glow */
        .osi-layer-card.active { border-color:var(--lc-color); box-shadow:0 0 20px var(--lc-glow), inset 0 0 30px var(--lc-glow-inner); }
        .osi-layer-card.active .lc-accent { box-shadow:0 0 12px var(--lc-color); }
        .osi-layer-card.active .lc-badge { box-shadow:0 0 16px var(--lc-glow); transform:scale(1.08); }
        .osi-layer-card.active .lc-status { color:var(--lc-color); background:var(--lc-glow-inner); }
        .osi-layer-card.done { border-color:rgba(255,255,255,0.08); }
        .osi-layer-card.done .lc-status { color:#81C784; }

        /* ── Travelling Dot ── */
        .osi-travel-dot {
          position:absolute; left:50%; width:10px; height:10px; border-radius:50%;
          background:#00CED1; box-shadow:0 0 14px #00CED1, 0 0 30px rgba(0,206,209,0.4);
          transform:translate(-50%,-50%); z-index:5; pointer-events:none;
          transition:top 0.5s cubic-bezier(0.4,0,0.2,1);
        }

        /* ── Packet Diagram ── */
        .osi-packet-diagram {
          display:flex; align-items:stretch; justify-content:center; min-height:70px;
          gap:0; border-radius:10px; overflow:hidden; position:relative;
          transition:all 0.4s ease;
        }
        .osi-pkt-block {
          display:flex; align-items:center; justify-content:center;
          padding:0.5rem 0.7rem; font-family:var(--font-mono); font-size:0.72rem;
          font-weight:700; text-transform:uppercase; letter-spacing:0.06em;
          position:relative; transition:all 0.4s cubic-bezier(0.4,0,0.2,1);
          border-right:1px solid rgba(0,0,0,0.3);
          animation:pktBlockIn 0.35s cubic-bezier(0.34,1.56,0.64,1) forwards;
        }
        @keyframes pktBlockIn {
          from { opacity:0; transform:scaleX(0); }
          to   { opacity:1; transform:scaleX(1); }
        }
        .osi-pkt-data {
          flex:1; min-width:120px; max-width:260px; text-align:center;
        }

        /* ── Step Info Card ── */
        .osi-step-info {
          background:rgba(0,0,0,0.2); border:1px solid rgba(255,255,255,0.06);
          border-radius:12px; padding:1.25rem; transition:all 0.3s ease;
        }
        .osi-step-info.glow { border-color:var(--si-color); box-shadow:0 0 20px var(--si-glow); }

        /* ── Progress Bar ── */
        .osi-progress {
          display:flex; gap:6px; align-items:center;
        }
        .osi-progress-dot {
          width:10px; height:10px; border-radius:50%; transition:all 0.3s ease;
          background:rgba(255,255,255,0.08); border:1px solid rgba(255,255,255,0.1);
        }
        .osi-progress-dot.done { background:#00CED1; border-color:#00CED1; box-shadow:0 0 8px rgba(0,206,209,0.5); }
        .osi-progress-dot.current { background:#FFB74D; border-color:#FFB74D; box-shadow:0 0 10px rgba(255,183,77,0.5); transform:scale(1.3); }
        .osi-progress-line {
          flex:1; height:2px; border-radius:9px; background:rgba(255,255,255,0.06);
          position:relative; overflow:hidden;
        }
        .osi-progress-fill {
          position:absolute; left:0; top:0; height:100%; border-radius:9px;
          background:linear-gradient(90deg, #00CED1, #7C4DFF);
          transition:width 0.4s ease;
        }
      </style>

      <div class="osi-viz">

        <!-- Header -->
        <div class="module-header">
          <div class="module-header__breadcrumb">
            <a href="#/">Home</a> › <span>Encapsulation & Decapsulation</span>
          </div>
          <h1 class="module-header__title">🌐 Encapsulation & Decapsulation Simulator</h1>
          <p class="module-header__description">
            Visualize how data is wrapped in protocol headers as it moves down the stack, and unwrapped as it moves up
          </p>
        </div>

        <!-- Mode Toggle -->
        <div class="osi-mode-toggle">
          <button class="osi-mode-btn ${this._phase === 'ENCAPSULATION' ? 'active' : ''}" id="btn-encap-mode">⬇ Encapsulation</button>
          <button class="osi-mode-btn ${this._phase !== 'ENCAPSULATION' ? 'active' : ''}" id="btn-deencap-mode">⬆ De-Encapsulation</button>
        </div>

        <!-- Transport Controls -->
        <div class="osi-controls">
          <button class="osi-ctrl-btn" id="btn-reset">⟲ Reset</button>
          <button class="osi-ctrl-btn" id="btn-prev">◀ Prev</button>
          <button class="osi-ctrl-btn primary" id="btn-play">▶ Play</button>
          <button class="osi-ctrl-btn primary" id="btn-pause" style="display:none;">⏸ Pause</button>
          <button class="osi-ctrl-btn" id="btn-next">Next ▶</button>
          <div style="flex:1;"></div>
          <div style="display:flex; gap:4px; align-items:center;">
            <span style="font-size:0.72rem; color:var(--color-text-muted); font-weight:600; margin-right:4px;">SPEED</span>
            ${[0.5, 1, 1.5, 2].map(s => `<button class="osi-speed-chip speed-btn ${s === this._playSpeed ? 'active' : ''}" data-speed="${s}">${s}x</button>`).join('')}
          </div>
        </div>

        <!-- Progress Indicator -->
        <div style="display:flex; align-items:center; gap:0.75rem; margin-bottom:1.5rem; padding:0 0.25rem;">
          <div class="osi-progress" style="flex:1;">
            ${[0, 1, 2, 3, 4, 5].map(i => `
              <div class="osi-progress-dot ${i < this._currentStep ? 'done' : ''} ${i === this._currentStep ? 'current' : ''}"></div>
              ${i < 5 ? '<div class="osi-progress-line"><div class="osi-progress-fill" style="width:' + (i < this._currentStep ? '100' : '0') + '%;"></div></div>' : ''}
            `).join('')}
          </div>
          <div style="font-family:var(--font-mono); font-size:0.85rem; color:var(--color-cyan); font-weight:700; white-space:nowrap;">
            Step <span id="step-counter">${this._currentStep}</span> / 5
          </div>
        </div>

        <!-- Main Visualization Grid -->
        <div style="display:grid; grid-template-columns:1fr 1fr; gap:1.5rem; margin-bottom:1.5rem;">

          <!-- LEFT: OSI Layer Stack -->
          <div style="position:relative;">
            <div style="font-size:0.72rem; text-transform:uppercase; letter-spacing:0.12em; color:var(--color-text-muted); font-weight:700; margin-bottom:0.75rem; padding-left:4px;">
              ${this._phase === 'ENCAPSULATION' ? '⬇ Sending Device — Layer Stack' : '⬆ Receiving Device — Layer Stack'}
            </div>
            <div id="stack-visual" style="display:flex; flex-direction:column; gap:8px; position:relative;">
              ${this._renderLayerCards()}
            </div>
          </div>

          <!-- RIGHT: Packet Diagram + Step Info -->
          <div style="display:flex; flex-direction:column; gap:1rem;">

            <!-- Packet Structure Diagram -->
            <div>
              <div style="font-size:0.72rem; text-transform:uppercase; letter-spacing:0.12em; color:var(--color-text-muted); font-weight:700; margin-bottom:0.75rem; padding-left:4px;">
                📦 Packet Structure
              </div>
              <div style="background:rgba(0,0,0,0.2); border:1px solid rgba(255,255,255,0.06); border-radius:12px; padding:1.25rem; min-height:100px; display:flex; align-items:center; justify-content:center;">
                <div id="packet-diagram" class="osi-packet-diagram" style="width:100%;">
                  ${this._renderPacketDiagram()}
                </div>
              </div>
            </div>

            <!-- Step Detail Info -->
            <div id="step-info" class="osi-step-info" style="--si-color:transparent; --si-glow:transparent;">
              ${this._renderStepInfo()}
            </div>

            <!-- Packet Size Meter -->
            <div style="background:rgba(0,0,0,0.2); border:1px solid rgba(255,255,255,0.06); border-radius:12px; padding:1rem;">
              <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:0.6rem;">
                <span style="font-size:0.72rem; text-transform:uppercase; letter-spacing:0.1em; color:var(--color-text-muted); font-weight:700;">📊 Total Packet Size</span>
                <span id="size-info" style="font-family:var(--font-mono); font-size:1.1rem; color:var(--color-cyan); font-weight:800;">12 bytes</span>
              </div>
              <div style="height:8px; background:rgba(255,255,255,0.05); border-radius:99px; overflow:hidden;">
                <div id="size-bar" style="height:100%; width:18%; background:linear-gradient(90deg,#00CED1,#7C4DFF); border-radius:99px; transition:width 0.4s ease;"></div>
              </div>
              <div style="display:flex; justify-content:space-between; margin-top:0.4rem;">
                <span style="font-size:0.65rem; color:var(--color-text-muted);">12B payload</span>
                <span style="font-size:0.65rem; color:var(--color-text-muted);">66B max</span>
              </div>
            </div>

          </div>
        </div>

        <!-- QUIZ MODE LAUNCH -->
        <div class="card" style="margin-bottom:2rem; background:linear-gradient(135deg, rgba(0,206,209,0.06), rgba(206,147,216,0.06)); border:1px solid rgba(0,206,209,0.2);">
          <div style="display:flex; align-items:center; justify-content:space-between; flex-wrap:wrap; gap:1rem;">
            <div>
              <h2 style="margin:0 0 0.4rem 0; font-size:1.2rem; display:flex; align-items:center; gap:0.5rem;">
                🎯 Quiz Mode
              </h2>
              <p style="color:var(--color-text-muted); margin:0; font-size:0.85rem; max-width:420px; line-height:1.5;">
                Test your OSI / TCP-IP knowledge with progressive difficulty, a 60-second timer, and spaced repetition for topics you need to review.
              </p>
            </div>
            <button class="btn btn-primary" id="btn-launch-quiz" style="
              padding:0.75rem 1.75rem; border-radius:12px; font-size:1rem; font-weight:700;
              background:linear-gradient(135deg, #00CED1, #7C4DFF);
              border:none; color:white; cursor:pointer;
              box-shadow:0 4px 20px rgba(0,206,209,0.3);
              transition:all 0.3s ease;
            " onmouseover="this.style.transform='translateY(-2px) scale(1.03)';this.style.boxShadow='0 6px 30px rgba(0,206,209,0.45)'" onmouseout="this.style.transform='none';this.style.boxShadow='0 4px 20px rgba(0,206,209,0.3)'">
              ▶ Start Quiz
            </button>
          </div>
        </div>

        <!-- Quiz Mount Point -->
        <div id="quiz-mode-root"></div>
      </div>
    `;

    this._bindEvents();
    this._updateDisplay();
  }

  /* ══════════════════════════════════════════
     LAYER CARDS
     ══════════════════════════════════════════ */
  _renderLayerCards() {
    return OSI_LAYERS.map((layer) => {
      const glowColor = layer.color + '40';
      const glowInner = layer.color + '10';
      return `
        <div class="osi-layer-card" data-layer="${layer.num}"
             style="--lc-color:${layer.color}; --lc-glow:${glowColor}; --lc-glow-inner:${glowInner};">
          <div class="lc-accent" style="background:${layer.color}44;"></div>
          <div class="lc-body">
            <div class="lc-badge" style="background:${layer.color};">L${layer.num}</div>
            <div class="lc-info">
              <div class="lc-name">${layer.icon} ${layer.name}</div>
              <div class="lc-sub">${layer.header}</div>
            </div>
            <div class="lc-pdu" style="background:${layer.color}18; color:${layer.color}; border:1px solid ${layer.color}33;">${layer.pdu}</div>
            <div class="lc-status" data-status>—</div>
          </div>
        </div>
      `;
    }).join('');
  }

  /* ══════════════════════════════════════════
     PACKET DIAGRAM — Nested header visualization
     ══════════════════════════════════════════ */
  _renderPacketDiagram() {
    if (this._currentStep === 0) {
      return `<div style="color:var(--color-text-muted); font-size:0.85rem; text-align:center; padding:1.5rem 0;">Waiting for simulation to start…</div>`;
    }

    const blocks = [];

    if (this._phase === 'ENCAPSULATION') {
      // Build outer → inner: each step adds one more header wrapping
      if (this._currentStep >= 5) blocks.push({ label: 'BITS', color: '#AB47BC', type: 'header', narrow: true });
      if (this._currentStep >= 4) blocks.push({ label: 'ETH', color: '#EC407A', type: 'header' });
      if (this._currentStep >= 3) blocks.push({ label: 'IP', color: '#26A69A', type: 'header' });
      if (this._currentStep >= 2) blocks.push({ label: 'TCP', color: '#5C6BC0', type: 'header' });
      blocks.push({ label: this._data, color: '#EF5350', type: 'data' });
      if (this._currentStep >= 4) blocks.push({ label: 'FCS', color: '#EC407A', type: 'trailer' });
    } else {
      // De-encap: start with FULL packet, strip one layer per step
      // Step 1: full packet (BITS+ETH+IP+TCP+DATA+FCS)
      // Step 2: BITS stripped → ETH+IP+TCP+DATA+FCS
      // Step 3: ETH+FCS stripped → IP+TCP+DATA
      // Step 4: IP stripped → TCP+DATA
      // Step 5: TCP stripped → clean DATA ✓
      const s = this._currentStep;
      if (s <= 1) blocks.push({ label: 'BITS', color: '#AB47BC', type: 'header', narrow: true });
      if (s <= 2) blocks.push({ label: 'ETH', color: '#EC407A', type: 'header' });
      if (s <= 3) blocks.push({ label: 'IP', color: '#26A69A', type: 'header' });
      if (s <= 4) blocks.push({ label: 'TCP', color: '#5C6BC0', type: 'header' });
      blocks.push({ label: s >= 5 ? '✓ ' + this._data : this._data, color: '#EF5350', type: 'data' });
      if (s <= 2) blocks.push({ label: 'FCS', color: '#EC407A', type: 'trailer' });
    }

    return blocks.map((b, i) => {
      const isData = b.type === 'data';
      const width = isData ? 'flex:1; min-width:100px;' : (b.narrow ? 'width:44px;' : 'width:60px;');
      const bg = isData ? `${b.color}22` : `${b.color}25`;
      const border = isData ? `border:2px solid ${b.color}` : `border-left:3px solid ${b.color}`;
      const fontSize = isData ? 'font-size:0.8rem;' : 'font-size:0.68rem;';
      const textColor = b.color;
      const delay = `animation-delay:${i * 60}ms;`;

      return `<div class="osi-pkt-block" style="
        ${width} background:${bg}; ${border}; color:${textColor}; ${fontSize} ${delay}
        ${isData ? 'letter-spacing:0; text-transform:none;' : ''}
      ">${b.label}</div>`;
    }).join('');
  }

  /* ══════════════════════════════════════════
     STEP INFO
     ══════════════════════════════════════════ */
  _renderStepInfo() {
    const steps = this._phase === 'ENCAPSULATION' ? ENCAP_STEPS : DEENCAP_STEPS;
    const step = steps[this._currentStep] || steps[0];
    const layer = OSI_LAYERS.find(l => l.num === step.activeLayer);
    const color = layer ? layer.color : 'var(--color-text-muted)';
    const icon = layer ? layer.icon : '📋';

    return `
      <div style="display:flex; align-items:center; gap:0.75rem; margin-bottom:0.75rem;">
        <div style="font-size:1.4rem;">${icon}</div>
        <div>
          <div style="font-size:0.65rem; text-transform:uppercase; letter-spacing:0.1em; color:${color}; font-weight:700;">
            Step ${this._currentStep} ${layer ? '— Layer ' + layer.num : ''}
          </div>
          <div style="font-size:1.05rem; font-weight:700; color:var(--color-text-primary);">${step.title}</div>
        </div>
      </div>
      <p style="color:var(--color-text-secondary); font-size:0.88rem; line-height:1.6; margin:0 0 0.75rem 0;">${step.desc}</p>
      ${step.fields ? `
        <div style="padding:0.6rem 0.8rem; background:rgba(0,0,0,0.2); border-radius:8px; font-family:var(--font-mono); font-size:0.78rem; color:${color}; border-left:3px solid ${color};">
          ${step.fields}
        </div>
      ` : ''}
    `;
  }

  /* ══════════════════════════════════════════
     UPDATE DISPLAY — called on every step change
     ══════════════════════════════════════════ */
  _updateDisplay() {
    const steps = this._phase === 'ENCAPSULATION' ? ENCAP_STEPS : DEENCAP_STEPS;
    const step = steps[this._currentStep] || steps[0];
    const cards = this.container?.querySelectorAll('.osi-layer-card');
    if (!cards) return;

    // Determine which layers have been processed
    const encapOrder = [7, 4, 3, 2, 1];
    const deencapOrder = [1, 2, 3, 4, 7];
    const order = this._phase === 'ENCAPSULATION' ? encapOrder : deencapOrder;

    cards.forEach(card => {
      const lnum = parseInt(card.dataset.layer);
      const orderIdx = order.indexOf(lnum);
      const statusEl = card.querySelector('[data-status]');
      const layer = OSI_LAYERS.find(l => l.num === lnum);

      card.classList.remove('active', 'done');

      if (orderIdx < this._currentStep && orderIdx !== this._currentStep - 1) {
        // Already processed
        card.classList.add('done');
        if (statusEl) {
          statusEl.textContent = this._phase === 'ENCAPSULATION' ? '✓ Added' : '✓ Removed';
        }
      } else if (orderIdx === this._currentStep - 1) {
        // Currently active
        card.classList.add('active');
        if (statusEl) {
          statusEl.textContent = this._phase === 'ENCAPSULATION'
            ? (lnum === 7 ? '● Created' : lnum === 1 ? '● Converting' : '● Adding')
            : (lnum === 7 ? '● Delivered' : lnum === 1 ? '● Receiving' : '● Removing');
        }
      } else {
        if (statusEl) statusEl.textContent = '—';
      }
    });

    // Update packet diagram
    const pktEl = this.container?.querySelector('#packet-diagram');
    if (pktEl) pktEl.innerHTML = this._renderPacketDiagram();

    // Update step info
    const infoEl = this.container?.querySelector('#step-info');
    if (infoEl) {
      const layer = OSI_LAYERS.find(l => l.num === step.activeLayer);
      if (layer) {
        infoEl.classList.add('glow');
        infoEl.style.setProperty('--si-color', layer.color + '55');
        infoEl.style.setProperty('--si-glow', layer.color + '20');
      } else {
        infoEl.classList.remove('glow');
        infoEl.style.setProperty('--si-color', 'transparent');
        infoEl.style.setProperty('--si-glow', 'transparent');
      }
      infoEl.innerHTML = this._renderStepInfo();
    }

    // Update packet size
    const sizeEl = this.container?.querySelector('#size-info');
    const sizeBar = this.container?.querySelector('#size-bar');
    if (sizeEl) {
      const base = 12;
      let total = base;
      if (this._phase === 'ENCAPSULATION') {
        if (this._currentStep >= 2) total += 20; // TCP
        if (this._currentStep >= 3) total += 20; // IP
        if (this._currentStep >= 4) total += 18; // ETH + FCS
      }
      sizeEl.textContent = `${total} bytes`;
      if (sizeBar) sizeBar.style.width = `${Math.round((total / 70) * 100)}%`;
    }

    // Update step counter
    const counterEl = this.container?.querySelector('#step-counter');
    if (counterEl) counterEl.textContent = this._currentStep;

    // Update progress dots
    this.container?.querySelectorAll('.osi-progress-dot').forEach((dot, i) => {
      dot.classList.remove('done', 'current');
      if (i < this._currentStep) dot.classList.add('done');
      else if (i === this._currentStep) dot.classList.add('current');
    });
    this.container?.querySelectorAll('.osi-progress-fill').forEach((fill, i) => {
      fill.style.width = (i < this._currentStep) ? '100%' : '0%';
    });
  }

  /* ══════════════════════════════════════════
     QUIZ MODE
     ══════════════════════════════════════════ */
  _launchQuizMode() {
    const root = this.container.querySelector('#quiz-mode-root');
    if (!root) return;
    if (this._quizInstance) {
      this._quizInstance.destroy();
      this._quizInstance = null;
    }
    this._quizInstance = new OsiQuizMode(root, () => {
      this._quizInstance = null;
    });
  }

  /* ══════════════════════════════════════════
     EVENT BINDING
     ══════════════════════════════════════════ */
  _bindEvents() {
    this.container.querySelector('#btn-reset')?.addEventListener('click', () => {
      this._clearAutoTimer();
      this._currentStep = 0;
      this._isPlaying = false;
      this._updatePlayButton();
      this._updateDisplay();
    });

    this.container.querySelector('#btn-prev')?.addEventListener('click', () => {
      if (this._currentStep > 0) {
        this._clearAutoTimer();
        this._currentStep--;
        this._isPlaying = false;
        this._updatePlayButton();
        this._updateDisplay();
      }
    });

    this.container.querySelector('#btn-next')?.addEventListener('click', () => {
      if (this._currentStep < 5) {
        this._currentStep++;
        this._updateDisplay();
      }
    });

    this.container.querySelector('#btn-play')?.addEventListener('click', () => {
      this._clearAutoTimer();
      this._isPlaying = true;
      this._updatePlayButton();
      this._autoPlay();
    });

    this.container.querySelector('#btn-pause')?.addEventListener('click', () => {
      this._isPlaying = false;
      this._clearAutoTimer();
      this._updatePlayButton();
    });

    this.container.querySelectorAll('.speed-btn').forEach(btn => {
      btn.addEventListener('click', (e) => {
        this.container.querySelectorAll('.speed-btn').forEach(b => b.classList.remove('active'));
        e.target.classList.add('active');
        this._playSpeed = parseFloat(e.target.dataset.speed);
      });
    });

    this.container.querySelector('#btn-encap-mode')?.addEventListener('click', () => {
      this._phase = 'ENCAPSULATION';
      this._currentStep = 0;
      this._isPlaying = false;
      this._clearAutoTimer();
      this._render();
    });

    this.container.querySelector('#btn-deencap-mode')?.addEventListener('click', () => {
      this._phase = 'DE-ENCAPSULATION';
      this._currentStep = 0;
      this._isPlaying = false;
      this._clearAutoTimer();
      this._render();
    });

    this.container.querySelector('#btn-launch-quiz')?.addEventListener('click', () => {
      this._launchQuizMode();
    });
  }

  _updatePlayButton() {
    const playBtn = this.container?.querySelector('#btn-play');
    const pauseBtn = this.container?.querySelector('#btn-pause');
    if (playBtn && pauseBtn) {
      if (this._isPlaying) {
        playBtn.style.display = 'none';
        pauseBtn.style.display = 'inline-flex';
      } else {
        playBtn.style.display = 'inline-flex';
        pauseBtn.style.display = 'none';
      }
    }
  }

  _autoPlay() {
    if (!this._isPlaying) return;
    if (this._currentStep < 5) {
      this._currentStep++;
      this._updateDisplay();
      const delay = 900 / this._playSpeed;
      this._clearAutoTimer();
      this._autoTimer = setTimeout(() => this._autoPlay(), delay);
    } else {
      this._isPlaying = false;
      this._updatePlayButton();
    }
  }

  _clearAutoTimer() {
    if (this._autoTimer) {
      clearTimeout(this._autoTimer);
      this._autoTimer = null;
    }
  }

  start() { }
  reset() { this._currentStep = 0; this._render(); }
  step() { }
  destroy() {
    this._clearAutoTimer();
    if (this._quizInstance) {
      this._quizInstance.destroy();
      this._quizInstance = null;
    }
    this.container = null;
  }
}

export default new OsiTcpipVisualizer();
